Move nounset so people w/o $EDITOR are warned.

diff --git a/bin/edit-password b/bin/edit-password
--- a/bin/edit-password
+++ b/bin/edit-password
@@ -1,6 +1,5 @@
 #!/bin/bash
 set -e
-set -o nounset
 
 usage() {
     cat >&2 <<EOM
@@ -24,6 +23,13 @@ if [ "$1" = "-h" -o "$1" = "--help" ]; then
     usage
     exit 0
 fi
+
+if [ -z "$EDITOR" ]; then
+    echo>&2 'error: $EDITOR is not set'
+    exit 2
+fi
+
+set -o nounset
 
 os_shred() {
     if [ $# -ne 1 ]; then
@@ -63,11 +69,6 @@ os_md5() {
             ;;
     esac
 }
-
-if [ -z "$EDITOR" ]; then
-    echo>&2 'error: $EDITOR is not set'
-    exit 2
-fi
 
 case $OSTYPE in
   darwin*)
