Sqash bugs in edit-password.

diff --git a/bin/edit-password b/bin/edit-password
--- a/bin/edit-password
+++ b/bin/edit-password
@@ -26,20 +26,20 @@ if [ "$1" = "-h" -o "$1" = "--help" ]; then
 fi
 
 os_shred() {
-    if [ $# -lt 1 ]; then
-        echo >&2 "cleanup FILE"
+    if [ $# -ne 1 ]; then
+        echo >&2 "os_shred FILE"
         exit 7
     fi
     file="$1"
 
     case $OSTYPE in
         linux-gnu)
-            echo >&2 "+ shred -uv '$file'"
-            shred -uv "$file"
+            echo >&2 "+ shred -u '$file'"
+            shred -u "$file" && echo>&2 "os_shred: $file: removed"
             ;;
         darwin*)
             echo >&2 "+ rm -P '$file'"
-            rm -P "$file"
+            rm -P "$file" && echo>&2 "os_shred: $file: removed"
             ;;
         *)
             echo >&2 "Unsupported \$OSTYPE: $OSTYPE"
@@ -64,7 +64,10 @@ os_md5() {
     esac
 }
 
-editor="$EDITOR"
+if [ -z "$EDITOR" ]; then
+    echo>&2 'error: $EDITOR is not set'
+    exit 2
+fi
 
 tmpfile="$(mktemp)" || exit 3
 
@@ -75,8 +78,8 @@ dir="$(dirname "$0")"
 echo>&2 "+ fetch-password $*"
 "$dir/fetch-password" $* > "$tmpfile"
 
-echo>&2 "+ fetch-password-recipients $*"
-recip_ids="$("$dir/fetch-password-recipients" $*)"
+echo>&2 "+ fetch-password-recipients --raw $*"
+recip_ids="$("$dir/fetch-password-recipients" --raw $*)"
 recip_opts=''
 for id in $recip_ids; do
     recip_opts="$recip_opts -r $id"
@@ -84,14 +87,10 @@ done
 
 orig_md5="$(os_md5 "$tmpfile")"
 
-echo>&2 "+ $editor '$tmpfile'"
-$editor "$tmpfile"
+echo>&2 "+ $EDITOR '$tmpfile'"
+$EDITOR "$tmpfile"
 
 post_md5="$(os_md5 "$tmpfile")"
-
-# DEBUG
-echo "pre:  $orig_md5"
-echo "post: $post_md5"
 
 if [ "$orig_md5" = "$post_md5" ]; then
     echo>&2 "No changes made."
@@ -101,3 +100,6 @@ fi
 echo>&2 "+ add-password $recip_opts $*"
 "$dir/add-password" $recip_opts $* < "$tmpfile"
 
+trap - EXIT
+os_shred "$tmpfile"
+echo 'Done.'
